package org.smurve.hsr2014.repo2;

import org.smurve.hsr2014.domain2.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

/**
 * You won't find an implementation of this interface, as it is auto-generated by
 * Spring Data JPA from the interface alone. Please refer to the documentation of
 * Spring Data Jpa for more information.
 */
public interface UserRepository extends JpaRepository<User, String>, CustomUserRepository {

    User findByUsername(String username);

    @Query("SELECT u FROM User u, IN (u.roles) AS r WHERE r.roleName=:roleName")
    List<User> findUsersByRole(@Param("roleName") String roleName);

    @Query("SELECT u FROM User u, IN (u.roles) AS r WHERE u.id=:userId and r.roleName=:roleName")
    User hasUserRole(@Param("userId") String userId, @Param("roleName") String roleName);
}
