application:
  title:  Smurve's Books

spring:
    datasource:
      dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      url: jdbc:mysql://localhost:3306/hsr2015
      databaseName:
      serverName: localhost
      username: root
      password: root
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

