/**
 * This class is generated by jOOQ
 */
package org.smurve.hsr2014.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.smurve.hsr2014.jooq.tables.Account;
import org.smurve.hsr2014.jooq.tables.Author;
import org.smurve.hsr2014.jooq.tables.Book;
import org.smurve.hsr2014.jooq.tables.Testrecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hsr2015 extends SchemaImpl {

	private static final long serialVersionUID = -1492652930;

	/**
	 * The reference instance of <code>hsr2015</code>
	 */
	public static final Hsr2015 HSR2015 = new Hsr2015();

	/**
	 * No further instances allowed
	 */
	private Hsr2015() {
		super("hsr2015");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Account.ACCOUNT,
			Author.AUTHOR,
			Book.BOOK,
			Testrecord.TESTRECORD);
	}
}
