/**
 * This class is generated by jOOQ
 */
package org.smurve.hsr2014.jooq;


import javax.annotation.Generated;

import org.smurve.hsr2014.jooq.tables.Account;
import org.smurve.hsr2014.jooq.tables.Author;
import org.smurve.hsr2014.jooq.tables.Book;
import org.smurve.hsr2014.jooq.tables.Testrecord;


/**
 * Convenience access to all tables in hsr2015
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table hsr2015.Account
	 */
	public static final Account ACCOUNT = org.smurve.hsr2014.jooq.tables.Account.ACCOUNT;

	/**
	 * The table hsr2015.Author
	 */
	public static final Author AUTHOR = org.smurve.hsr2014.jooq.tables.Author.AUTHOR;

	/**
	 * The table hsr2015.Book
	 */
	public static final Book BOOK = org.smurve.hsr2014.jooq.tables.Book.BOOK;

	/**
	 * The table hsr2015.TestRecord
	 */
	public static final Testrecord TESTRECORD = org.smurve.hsr2014.jooq.tables.Testrecord.TESTRECORD;
}
